<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CatatDuit — Finance Orbit</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script><style>
*{box-sizing:border-box}
html{scroll-behavior:smooth;scroll-padding-top:88px}
html,body{margin:0;min-height:100%;overflow-x:hidden;overflow-y:auto}
body{font-family:Inter,system-ui,sans-serif;background:#0b2947}
.cosmic{background:radial-gradient(circle at 78% 14%,rgba(55,120,180,.35),transparent 30%),radial-gradient(circle at 15% 10%,rgba(25,181,165,.2),transparent 28%),linear-gradient(135deg,#09253f 0%,#0d3457 52%,#123e65 100%);min-height:100vh;position:relative;overflow:visible}
.cosmic:before{content:'';position:absolute;inset:0;background-image:radial-gradient(#fff 1px,transparent 1px);background-size:48px 48px;opacity:.13;animation:stars 24s linear infinite;pointer-events:none}
.cosmic>*{position:relative;z-index:1}
@keyframes stars{to{background-position:48px 48px}}
@keyframes float{50%{transform:translateY(-16px)}}
.float{animation:float 6s ease-in-out infinite}
.glass{background:rgba(255,255,255,.065);border:1px solid rgba(255,255,255,.13);backdrop-filter:blur(14px)}
.site-nav{width:100%;background:rgba(9,37,63,.48);border-bottom:1px solid rgba(255,255,255,.08);backdrop-filter:blur(16px)}
.site-nav-inner{width:100%;max-width:1500px;margin:0 auto;padding:0 clamp(28px,6vw,104px)}
.page-inner{width:100%;max-width:1500px;margin:0 auto;padding-left:clamp(28px,6vw,104px);padding-right:clamp(28px,6vw,104px)}
section{scroll-margin-top:96px}
</style></head>
<body class="cosmic text-white">
<header class="site-nav sticky top-0 z-50"><nav class="site-nav-inner h-24 flex items-center justify-between">
<a href="#top" class="flex items-center gap-3" aria-label="CatatDuit Beranda"><div class="w-11 h-11 rounded-2xl bg-[#19B5A5] flex items-center justify-center text-2xl">✦</div><div><div class="font-extrabold text-xl">Catat<span class="text-[#58E0D1]">Duit</span></div><div class="text-[10px] tracking-[.25em] text-slate-400">FINANCE ORBIT</div></div></a>
<div class="hidden md:flex gap-8 text-sm text-slate-300"><a href="#fitur" class="hover:text-white transition">Fitur</a><a href="#cara" class="hover:text-white transition">Cara kerja</a><a href="#tentang" class="hover:text-white transition">Tentang</a></div>
<a href="{{ route('login') }}" class="rounded-xl border border-white/25 px-5 py-2.5 text-sm font-bold hover:bg-white/10 transition">Masuk</a>
</nav></header>
<main id="top" class="page-inner">
<section class="min-h-[650px] grid lg:grid-cols-2 gap-16 items-center py-14"><div><div class="inline-flex items-center gap-2 rounded-full glass px-4 py-2 text-xs text-[#9EF3E8] mb-7">✦ Kendalikan uangmu dari orbit mana pun</div><h1 class="text-5xl md:text-7xl font-extrabold leading-[1.05]">Keuanganmu,<br><span class="text-[#58E0D1]">lebih terarah.</span></h1><p class="mt-7 text-lg leading-8 text-slate-300 max-w-xl">Catat, rencanakan, dan pahami perjalanan uangmu dengan cara yang sederhana. Satu dashboard untuk menavigasi masa depan finansialmu.</p><div class="mt-9 flex flex-wrap gap-4"><a href="{{ route('dashboard') }}" class="rounded-xl bg-[#19B5A5] px-6 py-3.5 font-bold shadow-lg shadow-teal-900/30 hover:bg-[#2bc9b8] transition">Mulai menjelajah 🚀</a><a href="#fitur" class="rounded-xl border border-white/25 px-6 py-3.5 font-bold hover:bg-white/10 transition">Lihat fitur</a></div><div class="mt-10 flex flex-wrap gap-8 text-sm text-slate-400"><span>✓ Smart Entry</span><span>✓ Insight otomatis</span><span>✓ Tanpa ribet</span></div></div><div class="relative flex justify-center py-8"><div class="absolute w-96 h-96 rounded-full bg-[#19B5A5]/20 blur-3xl"></div><div class="float relative w-[390px] h-[390px] rounded-full glass flex items-center justify-center shadow-2xl"><div class="absolute w-[300px] h-[300px] rounded-full border border-[#58E0D1]/40"></div><div class="absolute w-3 h-3 rounded-full bg-[#58E0D1] top-12 right-12 shadow-[0_0_25px_#58E0D1]"></div><div class="absolute w-2 h-2 rounded-full bg-white bottom-20 left-12"></div><div class="text-center"><div class="text-8xl">🪐</div><div class="mt-4 font-bold text-lg">Your money. Your orbit.</div><div class="text-xs text-slate-300 mt-2">Navigasi finansial yang lebih tenang.</div></div></div></div></section>
<section id="fitur" class="py-24"><div class="text-center max-w-2xl mx-auto"><div class="text-xs tracking-[.3em] text-[#9EF3E8] mb-4">FITUR UTAMA</div><h2 class="text-3xl md:text-4xl font-extrabold">Semua kebutuhan finansialmu<br>dalam satu orbit.</h2><p class="mt-4 text-slate-300">CatatDuit membantu kamu melihat arah uang tanpa membuat pengelolaan keuangan terasa rumit.</p></div><div class="grid md:grid-cols-3 gap-6 mt-12"><div class="glass rounded-2xl p-7 hover:bg-white/10 transition"><div class="text-3xl mb-4">✦</div><h3 class="font-bold text-lg">Smart Entry</h3><p class="text-sm text-slate-300 mt-2 leading-6">Tulis “beli bakso 10k”, lalu CatatDuit membantu merapikannya menjadi catatan transaksi.</p></div><div class="glass rounded-2xl p-7 hover:bg-white/10 transition"><div class="text-3xl mb-4">◔</div><h3 class="font-bold text-lg">Insight jelas</h3><p class="text-sm text-slate-300 mt-2 leading-6">Lihat pola pengeluaran, pemasukan, dan sisa alokasi tanpa harus membaca angka yang rumit.</p></div><div class="glass rounded-2xl p-7 hover:bg-white/10 transition"><div class="text-3xl mb-4">◎</div><h3 class="font-bold text-lg">Target nyata</h3><p class="text-sm text-slate-300 mt-2 leading-6">Bawa tujuan finansialmu lebih dekat dengan progres yang mudah dipantau.</p></div></div></section>
<section id="cara" class="py-24"><div class="grid lg:grid-cols-2 gap-16 items-center"><div><div class="text-xs tracking-[.3em] text-[#9EF3E8] mb-4">CARA KERJA</div><h2 class="text-3xl md:text-4xl font-extrabold">Tiga langkah menuju<br>keuangan yang lebih tenang.</h2><p class="mt-5 text-slate-300 leading-8">Tidak perlu mulai dari spreadsheet yang rumit. Cukup catat, tinjau, lalu sesuaikan arah keuanganmu.</p></div><div class="space-y-4"><div class="glass rounded-2xl p-6 flex gap-5"><div class="w-11 h-11 rounded-xl bg-[#19B5A5] flex items-center justify-center font-extrabold">1</div><div><h3 class="font-bold">Catat dengan cepat</h3><p class="text-sm text-slate-300 mt-1">Gunakan Smart Entry atau input manual.</p></div></div><div class="glass rounded-2xl p-6 flex gap-5"><div class="w-11 h-11 rounded-xl bg-[#1F4E79] flex items-center justify-center font-extrabold">2</div><div><h3 class="font-bold">Tinjau laporan</h3><p class="text-sm text-slate-300 mt-1">Pahami ke mana uangmu pergi melalui grafik dan kategori.</p></div></div><div class="glass rounded-2xl p-6 flex gap-5"><div class="w-11 h-11 rounded-xl bg-white/10 flex items-center justify-center font-extrabold">3</div><div><h3 class="font-bold">Jaga arah finansial</h3><p class="text-sm text-slate-300 mt-1">Atur target, dana darurat, dan alokasi sesuai prioritas.</p></div></div></div></div></section>
<section id="tentang" class="py-24"><div class="glass rounded-3xl p-10 md:p-14 text-center"><div class="text-5xl mb-5">🚀</div><h2 class="text-3xl md:text-4xl font-extrabold">Siap mengorbitkan keuanganmu?</h2><p class="mt-4 text-slate-300 max-w-2xl mx-auto">CatatDuit dirancang untuk membantu kamu mengelola uang dengan lebih sadar, terarah, dan tenang.</p><a href="{{ route('dashboard') }}" class="inline-block mt-8 rounded-xl bg-[#19B5A5] px-7 py-3.5 font-bold hover:bg-[#2bc9b8] transition">Buka Dashboard Demo</a></div></section>
<footer class="border-t border-white/10 py-12 mt-8"><div class="grid md:grid-cols-4 gap-8"><div><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-xl bg-[#19B5A5] flex items-center justify-center text-xl">✦</div><div class="font-extrabold text-lg">Catat<span class="text-[#58E0D1]">Duit</span></div></div><p class="text-sm text-slate-400 mt-4 leading-6">Aplikasi pengelola keuangan pribadi dengan pendekatan Finance Orbit.</p></div><div><h4 class="font-bold mb-4">Produk</h4><ul class="space-y-2 text-sm text-slate-400"><li><a href="{{ route('dashboard') }}" class="hover:text-white">Dashboard</a></li><li><a href="{{ route('transaksi') }}" class="hover:text-white">Transaksi</a></li><li><a href="{{ route('laporan') }}" class="hover:text-white">Laporan</a></li><li><a href="{{ route('kategori') }}" class="hover:text-white">Kategori</a></li></ul></div><div><h4 class="font-bold mb-4">Perusahaan</h4><ul class="space-y-2 text-sm text-slate-400"><li><a href="#tentang" class="hover:text-white">Tentang</a></li><li><a href="#fitur" class="hover:text-white">Fitur</a></li><li><a href="#cara" class="hover:text-white">Cara kerja</a></li></ul></div><div><h4 class="font-bold mb-4">Kontak</h4><ul class="space-y-2 text-sm text-slate-400"><li>hello@catatduit.id</li><li>Surabaya, Indonesia</li></ul></div></div><div class="border-t border-white/10 mt-10 pt-6 flex flex-col md:flex-row justify-between gap-3 text-xs text-slate-500"><span>© 2026 CatatDuit. Semua hak dilindungi.</span><span>Dibuat untuk demo hackathon ✦ Finance Orbit</span></div></footer>
</main><script>document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth',block:'start')}}}));</script></body></html>